# Generated by Django 3.2 on 2022-04-08 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('prompt', models.TextField(default="What's the crack?", max_length=300, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('subs_list', models.ManyToManyField(blank=True, related_name='prompt_sub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.TextField(max_length=150)),
                ('created_on', models.DateField(auto_now=True)),
                ('prompt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wisecrack.prompt')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='sub_upvote', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
