# Generated by Django 3.2 on 2022-04-05 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wisecrack', '0002_auto_20220404_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='crack',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wisecrack.crack'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sub',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
