# Generated by Django 3.2 on 2022-04-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisecrack', '0003_auto_20220405_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crack',
            new_name='Prompt',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='crack',
            new_name='prompt',
        ),
    ]
