# Generated by Django 3.2 on 2022-04-06 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wisecrack', '0006_auto_20220405_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub',
            options={},
        ),
        migrations.RemoveField(
            model_name='sub',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='sub',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='sub_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
