# Generated by Django 3.2 on 2022-04-06 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wisecrack', '0009_alter_sub_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='sub_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
