# Generated by Django 3.2 on 2022-04-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisecrack', '0010_alter_sub_upvotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub',
            options={},
        ),
    ]
