# Generated by Django 3.2 on 2022-04-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisecrack', '0021_prompt_subs_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='subs_list',
            new_name='subs_list',
        ),
    ]
