# Generated by Django 3.2 on 2022-04-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisecrack', '0020_alter_sub_prompt'),
        ('wisecrack', '0022_rename_subs_total_prompt_subs_list'),
    ]

    operations = [
    ]
