# Generated by Django 3.2 on 2022-04-04 20:19

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wisecrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crack',
            name='text',
        ),
        migrations.AddField(
            model_name='crack',
            name='prompt',
            field=models.TextField(default="What's the crack?", max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name='crack',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.TextField(max_length=150)),
                ('upvotes', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wisecrack.user')),
            ],
            options={
                'ordering': ['-upvotes'],
            },
        ),
    ]
