# Generated by Django 3.2 on 2022-04-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisecrack', '0004_auto_20220405_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='date',
            field=models.DateField(),
        ),
    ]
