# Generated by Django 3.2 on 2022-04-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisecrack', '0016_sub_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='slug',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wisecrack.prompt', to_field='slug'),
        ),
    ]
